# Generated by Django 4.0.3 on 2022-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('idUser', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('fone', models.CharField(blank=True, max_length=15, null=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
